name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Run go mod tidy
        run: go mod tidy
      - name: Run Tests
<<<<<<< HEAD
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
=======
        run: go test ./... -cover
>>>>>>> ee681e6 (fixed CI git conflict)
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
      - name: Run Go Report Card
        uses: creekorful/goreportcard-action@v1.0
